[package]
name = "moonkey"
authors = [ "PureStake" ]
description = "Moonbeam Key Tool"
edition = "2021"
homepage = "https://moonbeam.network"
license = "GPL-3.0-only"
version = "0.1.1"

[[bin]]
name = "moonkey"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0.9", features = [ "derive" ] }
cli-opt = { package = "moonbeam-cli-opt", path = "../../../node/cli-opt", default-features = false }
