[package]
name = "moonkey"
authors = [ "PureStake" ]
description = "Moonbeam Key Tool"
edition = "2018"
homepage = "https://moonbeam.network"
license = "GPL-3.0-only"
version = "0.1.1"

[[bin]]
name = "moonkey"
path = "src/main.rs"

[dependencies]
cli-opt = { package = "moonbeam-cli-opt", path = "../../../node/cli-opt", default-features = false }
clap = { version = "3.1", features = ["derive"] }
