[package]
name = "pallet-author-mapping"
version = "1.0.0"
authors = ["PureStake"]
edition = "2018"
description = "Maps AuthorIds to AccountIds Useful for associating consensus authors with in-runtime accounts"

[dependencies]
pallet-author-inherent = { git = "https://github.com/purestake/cumulus", branch = "nimbus", default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }

# [dev-dependencies]
# sp-io = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
# sp-core = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }

[features]
default = ["std"]
std = [
	"pallet-author-inherent/std",
	"frame-support/std",
	"frame-system/std",
	"parity-scale-codec/std",
	"serde",
	"sp-std/std",
	"sp-runtime/std",
]
