[package]
name = "pallet-author-mapping"
version = "2.0.3"
authors = ["PureStake"]
edition = "2018"
description = "Maps AuthorIds to AccountIds Useful for associating consensus authors with in-runtime accounts"

[dependencies]
log = { version="0.4", default-features=false }
nimbus-primitives = { git="https://github.com/purestake/cumulus", branch="nimbus-polkadot-v0.9.9", default-features=false }
frame-support = { git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.9", default-features=false }
frame-system = { git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.9", default-features=false }
parity-scale-codec = { version="2.0.0", default-features=false, features=["derive"] }
serde = { version="1.0.101", optional=true }
sp-std = { git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.9", default-features=false }
sp-runtime = { git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.9", default-features=false }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.9", default-features = false, optional = true }

[dev-dependencies]
sp-io = { git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.9" }
sp-core = { git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.9" }
pallet-balances = { git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.9" }

[features]
default = ["std"]
std = [
	"log/std",
	"nimbus-primitives/std",
	"frame-support/std",
	"frame-system/std",
	"parity-scale-codec/std",
	"serde",
	"sp-std/std",
	"sp-runtime/std",
	"frame-benchmarking/std",
]
runtime-benchmarks = ["frame-benchmarking"]
try-runtime = ["frame-support/try-runtime"]
