[package]
name = "pallet-precompile-benchmarks"
authors = { workspace = true }
edition = "2021"
version = "0.1.0"

[dependencies]
# Moonbeam
storage-proof-primitives = { workspace = true }
pallet-evm-precompile-p256verify = { workspace = true }

# substrate
cumulus-primitives-core = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
parity-scale-codec = { workspace = true, features = ["derive"] }
scale-info = { workspace = true }
sp-core = { workspace = true }
sp-std = { workspace = true }

# Moonkit
pallet-relay-storage-roots = { workspace = true }

# Frontier
precompile-utils = { workspace = true }
fp-evm = { workspace = true }
evm = { workspace = true }

# Benchmarks
frame-benchmarking = { workspace = true, optional = true }

# Risc0
postcard = { workspace = true }
risc0-zkvm = { workspace = true }

[features]
default = ["std"]
std = [
    "cumulus-primitives-core/std",
    "frame-benchmarking/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-relay-storage-roots/std",
    "pallet-evm-precompile-p256verify/std",
    "precompile-utils/std",
    "parity-scale-codec/std",
    "risc0-zkvm/std",
    "scale-info/std",
    "sp-core/std",
    "sp-std/std",
    "fp-evm/std",
    "evm/std",
]

runtime-benchmarks = [
    "frame-benchmarking",
    "frame-system/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
]
try-runtime = ["frame-support/try-runtime"]
