[package]
authors = ["PureStake"]
edition = "2018"
name = "pallet-ethereum-chain-id"
version = "1.0.0"

[dependencies]
parity-scale-codec = { version = "2.2", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true, features = ["derive"] }

frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "crystalin-v0.9.9-block-response-length" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "crystalin-v0.9.9-block-response-length" }

[features]
default = ["std"]
std = [
    "parity-scale-codec/std",
    "serde",
    "frame-support/std",
    "frame-system/std",
]
try-runtime = ["frame-support/try-runtime"]
