[package]
name = "moonbeam-primitives-ext"
version = '0.1.0'
authors = ['PureStake']
edition = '2018'
homepage = 'https://moonbeam.network'
license = 'GPL-3.0-only'
repository = 'https://github.com/PureStake/moonbeam/'

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "2.2", default-features = false }
ethereum-types = { version = "0.11.0", default-features = false }
evm-tracing-events = { path = "../rpc/evm-tracing-events", default-features = false }
sp-runtime-interface = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.8", default-features = false }
sp-externalities = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.8", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.8", default-features = false }
tracing = { version = "0.1.25", optional = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"ethereum-types/std",
	"evm-tracing-events/std",
	"sp-runtime-interface/std",
	"sp-externalities/std",
	"sp-std/std",
	"tracing"
]