[package]
name = "moonbeam-extensions-evm"
version = '0.1.0'
authors = ['PureStake']
edition = '2018'
homepage = 'https://moonbeam.network'
license = 'GPL-3.0-only'
repository = 'https://github.com/PureStake/moonbeam/'

[dependencies]
fp-evm = { git = "https://github.com/purestake/frontier", default-features = false, branch = "notlesh-moonbeam-v0.7" }
pallet-evm = { git = "https://github.com/purestake/frontier", default-features = false, branch = "notlesh-moonbeam-v0.7" }
evm = { version = "0.26.0", default-features = false, features = ["with-codec"] }
evm-core = { version = "0.26.0", default-features = false, features = ["with-codec"] }
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "rococo-v1" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "rococo-v1" }
sp-io = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "rococo-v1" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "rococo-v1" }
moonbeam-rpc-primitives-debug = { path = "../../../primitives/rpc/debug", default-features = false }
ethereum-types = { version = "0.11.0", default-features = false }

[features]
default = ["std"]
std = [
	"evm/std",
	"evm/with-serde",
	"pallet-evm/std",
	"sp-core/std",
	"sp-std/std",
	"sp-runtime/std",
	"ethereum-types/std",
	"fp-evm/std",
	"moonbeam-rpc-primitives-debug/std"
]
