[package]
name = "pallet-proxy-genesis-companion"
authors = [ "PureStake" ]
description = "A simple pallet that expands pallet-proxy with a genesis configuration"
edition = "2021"
version = "0.1.0"

[dependencies]
frame-support = { git = "https://github.com/purestake/substrate", default-features = false , branch = "moonbeam-polkadot-v0.9.19" }
frame-system = { git = "https://github.com/purestake/substrate", default-features = false , branch = "moonbeam-polkadot-v0.9.19" }
pallet-proxy = { git = "https://github.com/purestake/substrate", default-features = false , branch = "moonbeam-polkadot-v0.9.19" }
parity-scale-codec = { version = "3.0.0", default-features = false }
scale-info = { version = "2.0", default-features = false, features = [ "derive" ] }
sp-runtime = { git = "https://github.com/purestake/substrate", default-features = false , branch = "moonbeam-polkadot-v0.9.19" }

[dev-dependencies]
serde = "1.0.124"

pallet-balances = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.19" }
sp-core = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.19" }
sp-io = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.19" }

[features]
default = [ "std" ]
std = [
	"frame-support/std",
	"frame-system/std",
	"pallet-proxy/std",
	"scale-info/std",
	"sp-runtime/std",
]
try-runtime = [ "frame-support/try-runtime" ]
