[package]
name = "pallet-evm-precompile-xcm-transactor"
authors = { workspace = true }
description = "A Precompile to make xcm-transactor accessible to pallet-evm"
edition = "2021"
version = "0.2.0"

[dependencies]

# Moonbeam
pallet-xcm-transactor = { workspace = true }
xcm-primitives = { workspace = true }

# Substrate
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
sp-weights = { workspace = true }
fp-evm = { workspace = true }
pallet-evm = { workspace = true, features = ["forbid-evm-reentrancy"] }
precompile-utils = { workspace = true, features = ["codec-xcm"] }

# Polkadot
xcm = { workspace = true }

# Cumulus
cumulus-primitives-core = { workspace = true }

[dev-dependencies]
derive_more = { workspace = true }
serde = { workspace = true }
sha3 = { workspace = true }

# Moonbeam
precompile-utils = { workspace = true, features = ["testing", "codec-xcm"] }
xcm-primitives = { workspace = true }

# Substrate
pallet-balances = { workspace = true, features = ["std", "insecure_zero_ed"] }
pallet-timestamp = { workspace = true }
parity-scale-codec = { workspace = true, features = ["max-encoded-len"] }
scale-info = { workspace = true, features = ["derive"] }
sp-io = { workspace = true }

# Polkadot
pallet-xcm = { workspace = true, features = ["std"] }
xcm-builder = { workspace = true }
xcm-executor = { workspace = true }

[features]
default = ["std"]
std = [
	"cumulus-primitives-core/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-evm/std",
	"pallet-xcm-transactor/std",
	"precompile-utils/std",
	"sp-core/std",
	"sp-std/std",
	"xcm-primitives/std",
]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
]
