[package]
authors = { workspace = true }
description = "Common constants for Moonbeam runtimes"
edition = "2021"
homepage = "https://moonbeam.network"
license = "GPL-3.0-only"
name = "moonbeam-runtime-constants"
version = "1.0.0"

[dependencies]

# Moonbeam
moonbeam-core-primitives = { workspace = true }

[features]
std = [
    "moonbeam-core-primitives/std"
]
runtime-benchmarks = []
try-runtime = []
