[package]
name = "summarize-precompile-checks"
authors = { workspace = true }
description = "Summarize precompile checks in all runtimes"
edition = "2021"
homepage = "https://moonbeam.network"
license = "GPL-3.0-only"
version = "0.0.0"

[dependencies]
clap = "4.0.18"
moonbase-runtime = { path = "../moonbase" }
moonbeam-runtime = { path = "../moonbeam" }
moonriver-runtime = { path = "../moonriver" }
precompile-utils = { workspace = true, features = [ "testing" ] }
serde_json = "1.0"
