[package]
authors = ['PureStake']
description = 'Moonbeam Core'
edition = '2018'
homepage = 'https://moonbeam.network'
license = 'Unlicense'
name = 'mb-core'
repository = 'https://github.com/PureStake/moonbeam/'
version = '0.1.0'

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
safe-mix = { default-features = false, version = '1.0.0' }
serde = { version = "1.0.101", optional = true }

# primitives
sp-core = { git = 'https://github.com/paritytech/substrate.git', rev = '4368fc66041b155050d68dccd43711ae01bc250b', default-features = false }
sp-io = { git = 'https://github.com/paritytech/substrate.git', rev = '4368fc66041b155050d68dccd43711ae01bc250b', default-features = false }
sp-runtime = { git = 'https://github.com/paritytech/substrate.git', rev = '4368fc66041b155050d68dccd43711ae01bc250b', default-features = false }
sp-std = { git = 'https://github.com/paritytech/substrate.git', rev = '4368fc66041b155050d68dccd43711ae01bc250b', default-features = false }
sp-staking = { git = 'https://github.com/paritytech/substrate.git', rev = '4368fc66041b155050d68dccd43711ae01bc250b', default-features = false }
node-primitives = { git = 'https://github.com/paritytech/substrate.git', rev = '4368fc66041b155050d68dccd43711ae01bc250b', default-features = false }

# frame dependencies
frame-support = { git = 'https://github.com/paritytech/substrate.git', rev = '4368fc66041b155050d68dccd43711ae01bc250b', default-features = false }
system = { package = 'frame-system', git = 'https://github.com/paritytech/substrate.git', rev = '4368fc66041b155050d68dccd43711ae01bc250b', default-features = false }
pallet-balances = { git = 'https://github.com/paritytech/substrate.git', rev = '4368fc66041b155050d68dccd43711ae01bc250b', default-features = false }
pallet-staking = { git = 'https://github.com/paritytech/substrate.git', rev = '4368fc66041b155050d68dccd43711ae01bc250b', default-features = false }

[features]
default = ['std']
std = [
    'codec/std',
    'safe-mix/std',
	"serde",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-staking/std",
	"node-primitives/std",
    'frame-support/std',
    'system/std',
	'pallet-balances/std',
	'pallet-staking/std'
]
