[package]
name = "pallet-migrations"
version = "0.1.0"
authors = ["PureStake"]
edition = "2018"
description = "migrations management pallet"

[dependencies]
frame-support = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para", default-features = false }
frame-system = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para", default-features = false }
log = "0.4"
sp-std = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para", default-features = false }
sp-runtime = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para", default-features = false }
parity-scale-codec = { version = "2.0.0", default-features = false }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }

[dev-dependencies]
environmental = "1.1.2"
sp-io = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }
sp-core = { git = "https://github.com/purestake/substrate", branch = "elois-sig-para" }

[features]
default = ["std"]
std = [
	"frame-support/std",
	"frame-system/std",
	"sp-std/std",
	"sp-runtime/std",
	"scale-info/std",
]
try-runtime = [
	"frame-support/try-runtime",
]
