[package]
name = "pallet-migrations"
authors = [ "PureStake" ]
description = "migrations management pallet"
edition = "2021"
version = "0.1.0"

[dependencies]
impl-trait-for-tuples = "0.2.1"
log = "0.4"

# Substrate
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
pallet-democracy = { workspace = true, default-features = false }
pallet-preimage = { workspace = true, default-features = false }
parity-scale-codec = { version = "3.0.0", default-features = false }
scale-info = { version = "2.0", default-features = false, features = [ "derive" ] }
sp-core = { workspace = true, default-features = false }
sp-io = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }

# Benchmarks
frame-benchmarking = { workspace = true, optional = true, default-features = false }


[dev-dependencies]
environmental = "1.1.2"
frame-benchmarking = { workspace = true }
pallet-balances = { workspace = true }
pallet-scheduler = { workspace = true }
sp-io = { workspace = true }

[features]
default = [ "std" ]
std = [
	"frame-support/std",
	"frame-system/std",
	"pallet-democracy/std",
	"pallet-preimage/std",
	"scale-info/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
runtime-benchmarks = [ "frame-benchmarking" ]
try-runtime = [ "frame-support/try-runtime" ]
