[package]
name = "moonbeam-rpc-txpool"
authors = [ "PureStake" ]
edition = "2018"
homepage = "https://moonbeam.network"
license = "GPL-3.0-only"
repository = "https://github.com/PureStake/moonbeam/"
version = "0.6.0"

[dependencies]
jsonrpc-core = "18.0.0"
rlp = "0.5"
serde = { version = "1.0", features = [ "derive" ] }
sha3 = "0.9"

# Moonbeam
moonbeam-rpc-core-txpool = { path = "../../rpc-core/txpool" }
moonbeam-rpc-primitives-txpool = { path = "../../../primitives/rpc/txpool" }

# Substrate
frame-system = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.15-1" }
sc-transaction-pool = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.15-1", features = [ "test-helpers" ] }
sc-transaction-pool-api = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.15-1" }
sp-api = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.15-1" }
sp-blockchain = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.15-1" }
sp-io = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.15-1" }
sp-runtime = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.15-1" }
sp-std = { git = "https://github.com/purestake/substrate", branch = "moonbeam-polkadot-v0.9.15-1" }

# Frontier
ethereum-types = "0.12.1"
fc-rpc = { git = "https://github.com/purestake/frontier", branch = "moonbeam-polkadot-v0.9.15-1", features = [ "rpc_binary_search_estimate" ] }
