name: Create client release ticket
on:
  workflow_dispatch:
    inputs:
      from:
        description: "Previous client version (eg. v0.35.0)"
        required: true
      to:
        description: "Next client version (eg. v0.36.0)"
        required: true

jobs:
  setup-scripts:
    runs-on: bare-metal
    steps:
      - uses: actions/checkout@v4
      - name: Upload tools
        uses: actions/upload-artifact@v4
        with:
          name: original-tools
          path: tools

  create_client_ticket:
    needs: ["setup-scripts"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Download Original Tools
        uses: actions/download-artifact@v4
        with:
          name: original-tools
          path: original-tools
      - name: Generate client release issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: original-tools
        run: |
          npm i
          npm run --silent print-client-release-issue -- --from ${{ github.event.inputs.from }} --to ${{ github.event.inputs.to }} | tee ../client-release-issue.md
      - name: Create version bump issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: client ${{ github.event.inputs.to }} release
          content-filepath: ./client-release-issue.md
          labels: |
            automated issue
