name: Create client release ticket
on:
  workflow_dispatch:
    inputs:
      from:
        description: "Previous client version (eg. v0.35.0)"
        required: true
      to:
        description: "Next client version (eg. v0.36.0)"
        required: true

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  setup-scripts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Upload tools
        uses: actions/upload-artifact@v6
        with:
          name: original-tools
          path: tools

  create_client_ticket:
    needs: ["setup-scripts"]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: "test/.nvmrc"
      - name: Download Original Tools
        uses: actions/download-artifact@v7
        with:
          name: original-tools
          path: original-tools
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Generate client release issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: original-tools
        run: |
          pnpm install --ignore-workspace 
          pnpm run --silent print-client-release-issue --from ${{ github.event.inputs.from }} --to ${{ github.event.inputs.to }} | tee ../client-release-issue.md
      - name: Create version bump issue
        uses: peter-evans/create-issue-from-file@v6
        with:
          title: client ${{ github.event.inputs.to }} release
          content-filepath: ./client-release-issue.md
          labels: |
            automated issue
