name: Enforce PR labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  enforce-noteworthiness-label:
    runs-on: ubuntu-latest
    steps:
      - uses: yogevbd/enforce-label-action@2.2.0
        with:
          REQUIRED_LABELS_ANY: "B0-silent,B5-clientnoteworthy,B7-runtimenoteworthy"
          REQUIRED_LABELS_ALL: ""
          BANNED_LABELS: ""
  enforce-auditability-label:
    runs-on: ubuntu-latest
    steps:
      - uses: yogevbd/enforce-label-action@2.2.0
        with:
          REQUIRED_LABELS_ANY: "D1-audited,D5-nicetohaveaudit,D9-needsaudit,D11-notlive,D12-trivial"
          REQUIRED_LABELS_ALL: ""
          BANNED_LABELS: ""
