name: Enforce PR labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  enforce-noteworthiness-label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: yogevbd/enforce-label-action@2.2.2
        with:
          REQUIRED_LABELS_ANY: "B0-silent,B5-clientnoteworthy,B7-runtimenoteworthy"
          REQUIRED_LABELS_ALL: ""
          BANNED_LABELS: ""
      - name: Verify breaking changes label
        if: contains(github.event.pull_request.labels.*.name, 'B5-clientnoteworthy') || contains(github.event.pull_request.labels.*.name, 'B7-runtimenoteworthy')
        uses: yogevbd/enforce-label-action@2.2.2
        with:
          REQUIRED_LABELS_ANY: "breaking,not-breaking"
          REQUIRED_LABELS_ALL: ""
          BANNED_LABELS: ""
  enforce-auditability-label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: yogevbd/enforce-label-action@2.2.2
        with:
          REQUIRED_LABELS_ANY: "D1-auditedüëç,D5-nicetohaveaudit‚ö†Ô∏è,D9-needsauditüëÆ,D2-notlive,D3-trivial"
          REQUIRED_LABELS_ALL: ""
          BANNED_LABELS: ""
