name: Create runtime release ticket
on:
  workflow_dispatch:
    inputs:
      from:
        description: "Previous runtime version (example: 1103)"
        required: true
      to:
        description: "Next runtime version (example: 1201)"
        required: true
      client:
        description: "Last client release version"
        required: true

jobs:
  create_runtime_ticket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Generate runtime release issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd tools
          npm i
          npm run --silent print-runtime-release-issue -- --from ${{ github.event.inputs.from }} --to ${{ github.event.inputs.to }} --client ${{ github.event.inputs.client }} | tee ../runtime-release-issue.md
      - name: Create version bump issue
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: runtime-${{ github.event.inputs.to }} release
          content-filepath: ./runtime-release-issue.md
          labels: |
            automated issue
