name: Create runtime release ticket
on:
  workflow_dispatch:
    inputs:
      from:
        description: "Previous runtime spec version (example: 1103)"
        required: true
      to:
        description: "Next runtime spec version (example: 1201)"
        required: true
      client:
        description: "Last client release version (example: v0.34.0)"
        required: true

jobs:
  setup-scripts:
    runs-on: bare-metal
    steps:
      - uses: actions/checkout@v4
      - name: Upload tools
        uses: actions/upload-artifact@v4
        with:
          name: original-tools
          path: tools

  create_runtime_ticket:
    needs: ["setup-scripts"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Download Original Tools
        uses: actions/download-artifact@v4
        with:
          name: original-tools
          path: original-tools
      - name: Generate runtime release issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: original-tools
        run: |
          npm i
          npm run --silent print-runtime-release-issue -- --from ${{ github.event.inputs.from }} --to ${{ github.event.inputs.to }} --client ${{ github.event.inputs.client }} | tee ../runtime-release-issue.md
      - name: Create version bump issue
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: runtime-${{ github.event.inputs.to }} release
          content-filepath: ./runtime-release-issue.md
          labels: |
            automated issue
